name: 'Build, Test and Ktlint Check'
description: 'Run Gradle build, tests and ktlint check'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build Gradle
      uses: ./gradlew build

    - name: Run Tests
      shell: bash
      run: ./gradlew test

    - name: Ktlint Check
      shell: bash
      run: ./gradlew ktlintCheck
