name: GraphQL Generator Action

on:
  pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test and Ktlint Check
        uses: ./  # Refers to the current repository for the action
